spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: dev
  application:
    name: service-A-app
server:
  port: 8081


xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appName: service-A-app
      ip: 127.0.0.1
      port: 9999
